# Generated by Django 5.1.2 on 2024-10-10 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, default='Возраст не указан', null=True),
        ),
    ]
