# Generated by Django 5.1.2 on 2024-10-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chat_message_chat_users_chat_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
