# Generated by Django 5.1.2 on 2024-10-10 16:30

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breeder',
            field=models.ForeignKey(default=accounts.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL),
        ),
    ]
